---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте. 
  - Пользователь должен иметь возможность играть как зарегистрированный пользователь, так и без регистрации.
  - Пользователь должен иметь возможность зарегистрироваться через учетные записи GITHUB/DISCORD.
  - Пользователь должен иметь возможность решать задачи на скорость против другого пользователя в режиме реального времени.
  - Пользователь, который выполнил задачу быстрее - побеждает.
  - Пользователи должны иметь возможность видеть друг у друга редактор с кодом.
  - Пользователи должны иметь возможность видеть друг у друга вывод тестов.
  - Пользователь должен иметь возможность менять язык программирования во время решения.
  - Пользователь должен иметь возможность играть с любым человеком, с ботом или другом (игра будет доступна по ссылке).
  - Пользователь должен иметь возможность выбрать игру по уровню сложности.
  - Пользователь должен иметь возможность при создании игры выбрать конкретную игру.
  - Пользователь должен иметь возможность при создании игры использовать теги как фильтры.
  - Пользователь должен иметь возможность при создании игры установить время её продолжительности.
  - Пользователь должен иметь возможность ознакомиться с правилами игры - всплывающие подсказки в разных частях поля задачи.
  - Пользователь должен иметь возможность менять язык задачи — русский или английский.
  - Пользователь должен иметь возможность просматривать профиль другого пользователя.
  - Пользователь должен иметь возможность следить за ходом игры других пользователей.
  - Пользователь должен быть зарегистирован, чтобы иметь возможность обащаться в чате игры с другими пользователями.
  - Пользователь должен иметь возможность смотреть завершенную игру в записи (редактор для ввода кода выглядит как проигрыватель).
  - Пользователь должен иметь возможность получать очки, на основе которых строится рейтинг за неделю, месяц и за всё время.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен открываться на мобильном устройстве и им удобно было пользоваться.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Во время просмотра завершенной игры пользователи не могут ничего редактировать и писать в чате.
  - Пользователи не могут написать в поле свою задачу для игры, а выбрать только существующую или случайную.
  - Во время игры пользователь не может редактировать код другого пользователя.
 
